<x-backend.layout>
    <x-slot:title>Menu Trash</x-slot:title>
    <div class="p-3 xl:p-6">
        <div class="mt-1 mb-6 flex items-center justify-between"><p class="text-xl font-bold uppercase">thung rac menu</p></div>
        <form method="GET" action=""><div class="flex gap-3"><div class="flex flex-3"><input type="text" name="name" placeholder="Search menu" class="w-full rounded-l-md bg-white px-4 py-2 text-black focus:outline-none" value="{{ request('name') }}"><button class="rounded-r-md bg-orange-400 px-5 font-semibold text-black hover:bg-orange-500"><i class="fa-solid fa-magnifying-glass"></i></button></div><div class="flex-1"><select name="status" class="w-full flex-1 rounded-lg border bg-white px-4 py-2" onchange="this.form.submit()"><option value="">Status</option><option value="0" {{ request('status') == '0' ? 'selected' : '' }}>Inactive</option><option value="1" {{ request('status') == '1' ? 'selected' : '' }}>Active</option></select></div><div class="h-6 self-center border-l border-black"></div><div><select name="sort_by" class="w-full flex-1 rounded-lg border bg-white px-4 py-2" onchange="this.form.submit()"><option value="">Sap xep</option><option value="asc" {{ request('sort_by') == 'asc' ? 'selected' : '' }}>Ten tang dan</option><option value="desc" {{ request('sort_by') == 'desc' ? 'selected' : '' }}>Ten giam dan</option></select></div><a href="{{ route('menu.trash') }}" class="self-center rounded-lg bg-white px-4 py-2">Reset</a></div></form>
        <div class="flex-auto"><div class="overflow-x-auto"><table class="mt-3 w-full border-collapse rounded-lg bg-white"><thead><tr><th class="px-3 py-1 text-center">ID</th><th class="px-3 py-1 text-center">Name</th><th class="px-3 py-1 text-center">Link</th><th class="px-3 py-1 text-center">Table ID</th><th class="px-3 py-1 text-center">Type</th><th class="px-3 py-1 text-center">Status</th><th class="px-3 py-1 text-center">Actions</th></tr></thead><tbody>@forelse ($menus as $menu)<tr class="border-t border-gray-200 text-center hover:bg-gray-50"><td class="px-1 py-3">{{ $menu->id }}</td><td class="px-1 py-3">{{ $menu->name }}</td><td class="px-1 py-3">{{ $menu->link }}</td><td class="px-1 py-3">{{ $menu->table_id }}</td><td class="px-1 py-3">{{ $menu->type }}</td><td class="px-1 py-3">{{ $menu->status }}</td><td class="align-middle px-1 py-3"><div class="flex flex-nowrap gap-2"><div class="rounded-lg p-3 text-sm shadow hover:bg-gray-100"><a href="#"><i class="fa-solid fa-arrows-rotate"></i><span class="ml-1 hidden xl:inline">Khoi phuc</span></a></div><div class="rounded-lg p-3 text-sm text-red-500 shadow hover:bg-gray-100"><a href="#"><i class="fa-solid fa-trash"></i></a></div></div></td></tr>@empty<tr><td class="p-6 text-center" colspan="7">Danh sach menu trong thung rac rong</td></tr>@endforelse</tbody></table></div></div>
        <div class="mt-4">{{ $menus->links() }}</div>
    </div>
</x-backend.layout>
